version: "3"
services:
  truffle:
    image: alblockmed/bmdcontract-deployment:latest
    stdin_open: true
    tty: true
    env_file:
      ./truffle.env
    networks:
      local-truffle-env:
        aliases:
          - truffle

  ganache:
    image: blcksync/ganache-cli:latest
    ports:
      - 7545:7545
    networks:
      local-truffle-env:
        aliases:
          - ganache

networks:
  local-truffle-env:
